server:
  port: 8081

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: ${JWT_SECRET:ThisIsADemoSecretKeyForPOC_PleaseChangeInProd_1234567890}
  expiration-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.manikanta: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s